// Generated by gencpp from file kamerider_image_msgs/GenderDetection.msg
// DO NOT EDIT!


#ifndef KAMERIDER_IMAGE_MSGS_MESSAGE_GENDERDETECTION_H
#define KAMERIDER_IMAGE_MSGS_MESSAGE_GENDERDETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kamerider_image_msgs
{
template <class ContainerAllocator>
struct GenderDetection_
{
  typedef GenderDetection_<ContainerAllocator> Type;

  GenderDetection_()
    : male_num(0)
    , female_num(0)
    , sit_num(0)
    , stand_num(0)  {
    }
  GenderDetection_(const ContainerAllocator& _alloc)
    : male_num(0)
    , female_num(0)
    , sit_num(0)
    , stand_num(0)  {
  (void)_alloc;
    }



   typedef int8_t _male_num_type;
  _male_num_type male_num;

   typedef int8_t _female_num_type;
  _female_num_type female_num;

   typedef int8_t _sit_num_type;
  _sit_num_type sit_num;

   typedef int8_t _stand_num_type;
  _stand_num_type stand_num;





  typedef boost::shared_ptr< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> const> ConstPtr;

}; // struct GenderDetection_

typedef ::kamerider_image_msgs::GenderDetection_<std::allocator<void> > GenderDetection;

typedef boost::shared_ptr< ::kamerider_image_msgs::GenderDetection > GenderDetectionPtr;
typedef boost::shared_ptr< ::kamerider_image_msgs::GenderDetection const> GenderDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kamerider_image_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'kamerider_image_msgs': ['/home/wen/rse/catkin_ws/src/kamerider_image/kamerider_image_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "105a02752dd5a1e4af0ec4122f3b9eba";
  }

  static const char* value(const ::kamerider_image_msgs::GenderDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x105a02752dd5a1e4ULL;
  static const uint64_t static_value2 = 0xaf0ec4122f3b9ebaULL;
};

template<class ContainerAllocator>
struct DataType< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kamerider_image_msgs/GenderDetection";
  }

  static const char* value(const ::kamerider_image_msgs::GenderDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 male_num\n\
int8 female_num\n\
int8 sit_num\n\
int8 stand_num\n\
";
  }

  static const char* value(const ::kamerider_image_msgs::GenderDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.male_num);
      stream.next(m.female_num);
      stream.next(m.sit_num);
      stream.next(m.stand_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenderDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kamerider_image_msgs::GenderDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kamerider_image_msgs::GenderDetection_<ContainerAllocator>& v)
  {
    s << indent << "male_num: ";
    Printer<int8_t>::stream(s, indent + "  ", v.male_num);
    s << indent << "female_num: ";
    Printer<int8_t>::stream(s, indent + "  ", v.female_num);
    s << indent << "sit_num: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sit_num);
    s << indent << "stand_num: ";
    Printer<int8_t>::stream(s, indent + "  ", v.stand_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAMERIDER_IMAGE_MSGS_MESSAGE_GENDERDETECTION_H
