// Generated by gencpp from file kamerider_image_msgs/mission.msg
// DO NOT EDIT!


#ifndef KAMERIDER_IMAGE_MSGS_MESSAGE_MISSION_H
#define KAMERIDER_IMAGE_MSGS_MESSAGE_MISSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kamerider_image_msgs
{
template <class ContainerAllocator>
struct mission_
{
  typedef mission_<ContainerAllocator> Type;

  mission_()
    : mission_type()
    , mission_name()  {
    }
  mission_(const ContainerAllocator& _alloc)
    : mission_type(_alloc)
    , mission_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mission_type_type;
  _mission_type_type mission_type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mission_name_type;
  _mission_name_type mission_name;





  typedef boost::shared_ptr< ::kamerider_image_msgs::mission_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kamerider_image_msgs::mission_<ContainerAllocator> const> ConstPtr;

}; // struct mission_

typedef ::kamerider_image_msgs::mission_<std::allocator<void> > mission;

typedef boost::shared_ptr< ::kamerider_image_msgs::mission > missionPtr;
typedef boost::shared_ptr< ::kamerider_image_msgs::mission const> missionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kamerider_image_msgs::mission_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kamerider_image_msgs::mission_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kamerider_image_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'kamerider_image_msgs': ['/home/wen/rse/catkin_ws/src/kamerider_image/kamerider_image_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kamerider_image_msgs::mission_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kamerider_image_msgs::mission_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kamerider_image_msgs::mission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kamerider_image_msgs::mission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kamerider_image_msgs::mission_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kamerider_image_msgs::mission_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kamerider_image_msgs::mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d58fdcb61ba622ce7ed121da079b668";
  }

  static const char* value(const ::kamerider_image_msgs::mission_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d58fdcb61ba622cULL;
  static const uint64_t static_value2 = 0xe7ed121da079b668ULL;
};

template<class ContainerAllocator>
struct DataType< ::kamerider_image_msgs::mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kamerider_image_msgs/mission";
  }

  static const char* value(const ::kamerider_image_msgs::mission_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kamerider_image_msgs::mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mission_type\n\
string mission_name\n\
";
  }

  static const char* value(const ::kamerider_image_msgs::mission_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kamerider_image_msgs::mission_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission_type);
      stream.next(m.mission_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mission_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kamerider_image_msgs::mission_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kamerider_image_msgs::mission_<ContainerAllocator>& v)
  {
    s << indent << "mission_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mission_type);
    s << indent << "mission_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mission_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAMERIDER_IMAGE_MSGS_MESSAGE_MISSION_H
