(cl:defpackage face_detection-srv
  (:use )
  (:export
   "FACERECOGNITIONTRAIN"
   "<FACERECOGNITIONTRAIN-REQUEST>"
   "FACERECOGNITIONTRAIN-REQUEST"
   "<FACERECOGNITIONTRAIN-RESPONSE>"
   "FACERECOGNITIONTRAIN-RESPONSE"
  ))

