// Generated by gencpp from file face_detection/FaceRecognitionTrain.msg
// DO NOT EDIT!


#ifndef FACE_DETECTION_MESSAGE_FACERECOGNITIONTRAIN_H
#define FACE_DETECTION_MESSAGE_FACERECOGNITIONTRAIN_H

#include <ros/service_traits.h>


#include <face_detection/FaceRecognitionTrainRequest.h>
#include <face_detection/FaceRecognitionTrainResponse.h>


namespace face_detection
{

struct FaceRecognitionTrain
{

typedef FaceRecognitionTrainRequest Request;
typedef FaceRecognitionTrainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FaceRecognitionTrain
} // namespace face_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::face_detection::FaceRecognitionTrain > {
  static const char* value()
  {
    return "c47a3ceb75cbe248d69217439e66a8e2";
  }

  static const char* value(const ::face_detection::FaceRecognitionTrain&) { return value(); }
};

template<>
struct DataType< ::face_detection::FaceRecognitionTrain > {
  static const char* value()
  {
    return "face_detection/FaceRecognitionTrain";
  }

  static const char* value(const ::face_detection::FaceRecognitionTrain&) { return value(); }
};


// service_traits::MD5Sum< ::face_detection::FaceRecognitionTrainRequest> should match 
// service_traits::MD5Sum< ::face_detection::FaceRecognitionTrain > 
template<>
struct MD5Sum< ::face_detection::FaceRecognitionTrainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::face_detection::FaceRecognitionTrain >::value();
  }
  static const char* value(const ::face_detection::FaceRecognitionTrainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::face_detection::FaceRecognitionTrainRequest> should match 
// service_traits::DataType< ::face_detection::FaceRecognitionTrain > 
template<>
struct DataType< ::face_detection::FaceRecognitionTrainRequest>
{
  static const char* value()
  {
    return DataType< ::face_detection::FaceRecognitionTrain >::value();
  }
  static const char* value(const ::face_detection::FaceRecognitionTrainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::face_detection::FaceRecognitionTrainResponse> should match 
// service_traits::MD5Sum< ::face_detection::FaceRecognitionTrain > 
template<>
struct MD5Sum< ::face_detection::FaceRecognitionTrainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::face_detection::FaceRecognitionTrain >::value();
  }
  static const char* value(const ::face_detection::FaceRecognitionTrainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::face_detection::FaceRecognitionTrainResponse> should match 
// service_traits::DataType< ::face_detection::FaceRecognitionTrain > 
template<>
struct DataType< ::face_detection::FaceRecognitionTrainResponse>
{
  static const char* value()
  {
    return DataType< ::face_detection::FaceRecognitionTrain >::value();
  }
  static const char* value(const ::face_detection::FaceRecognitionTrainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FACE_DETECTION_MESSAGE_FACERECOGNITIONTRAIN_H
