# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from salience/RectArray.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import salience.msg

class RectArray(genpy.Message):
  _md5sum = "2a26a8cb81778da4e083813232578748"
  _type = "salience/RectArray"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Rect[] bboxes

================================================================================
MSG: salience/Rect
# opencv Rect data type, x-y is center point
float64 x0
float64 y0
float64 x1
float64 y1
int32 id
"""
  __slots__ = ['bboxes']
  _slot_types = ['salience/Rect[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bboxes

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RectArray, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.bboxes is None:
        self.bboxes = []
    else:
      self.bboxes = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.bboxes)
      buff.write(_struct_I.pack(length))
      for val1 in self.bboxes:
        _x = val1
        buff.write(_get_struct_4di().pack(_x.x0, _x.y0, _x.x1, _x.y1, _x.id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.bboxes is None:
        self.bboxes = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.bboxes = []
      for i in range(0, length):
        val1 = salience.msg.Rect()
        _x = val1
        start = end
        end += 36
        (_x.x0, _x.y0, _x.x1, _x.y1, _x.id,) = _get_struct_4di().unpack(str[start:end])
        self.bboxes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.bboxes)
      buff.write(_struct_I.pack(length))
      for val1 in self.bboxes:
        _x = val1
        buff.write(_get_struct_4di().pack(_x.x0, _x.y0, _x.x1, _x.y1, _x.id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.bboxes is None:
        self.bboxes = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.bboxes = []
      for i in range(0, length):
        val1 = salience.msg.Rect()
        _x = val1
        start = end
        end += 36
        (_x.x0, _x.y0, _x.x1, _x.y1, _x.id,) = _get_struct_4di().unpack(str[start:end])
        self.bboxes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4di = None
def _get_struct_4di():
    global _struct_4di
    if _struct_4di is None:
        _struct_4di = struct.Struct("<4di")
    return _struct_4di
