// Generated by gencpp from file salience/RectArray.msg
// DO NOT EDIT!


#ifndef SALIENCE_MESSAGE_RECTARRAY_H
#define SALIENCE_MESSAGE_RECTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <salience/Rect.h>

namespace salience
{
template <class ContainerAllocator>
struct RectArray_
{
  typedef RectArray_<ContainerAllocator> Type;

  RectArray_()
    : bboxes()  {
    }
  RectArray_(const ContainerAllocator& _alloc)
    : bboxes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::salience::Rect_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::salience::Rect_<ContainerAllocator> >::other >  _bboxes_type;
  _bboxes_type bboxes;





  typedef boost::shared_ptr< ::salience::RectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::salience::RectArray_<ContainerAllocator> const> ConstPtr;

}; // struct RectArray_

typedef ::salience::RectArray_<std::allocator<void> > RectArray;

typedef boost::shared_ptr< ::salience::RectArray > RectArrayPtr;
typedef boost::shared_ptr< ::salience::RectArray const> RectArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::salience::RectArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::salience::RectArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace salience

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'salience': ['/home/wen/rse/catkin_ws/src/salience/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::salience::RectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::salience::RectArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::salience::RectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::salience::RectArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::salience::RectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::salience::RectArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::salience::RectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a26a8cb81778da4e083813232578748";
  }

  static const char* value(const ::salience::RectArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a26a8cb81778da4ULL;
  static const uint64_t static_value2 = 0xe083813232578748ULL;
};

template<class ContainerAllocator>
struct DataType< ::salience::RectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "salience/RectArray";
  }

  static const char* value(const ::salience::RectArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::salience::RectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Rect[] bboxes\n\
\n\
================================================================================\n\
MSG: salience/Rect\n\
# opencv Rect data type, x-y is center point\n\
float64 x0\n\
float64 y0\n\
float64 x1\n\
float64 y1\n\
int32 id\n\
";
  }

  static const char* value(const ::salience::RectArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::salience::RectArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bboxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RectArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::salience::RectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::salience::RectArray_<ContainerAllocator>& v)
  {
    s << indent << "bboxes[]" << std::endl;
    for (size_t i = 0; i < v.bboxes.size(); ++i)
    {
      s << indent << "  bboxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::salience::Rect_<ContainerAllocator> >::stream(s, indent + "    ", v.bboxes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SALIENCE_MESSAGE_RECTARRAY_H
